app.name=Eternity TTRPG Helper
app.version=${project.version}
update.url=
update.github.repo=
update.github.latestReleaseUrl=
update.github.assetName=EternityTTRPG.jar
update.github.sha256AssetName=EternityTTRPG.jar.sha256
